### ISSUE TITLE
HOTA on MOT Challenge Benchmark

### ISSUE THREAD

**Issue by jiaweihe1996** [JonathonLuiten/HOTA-metrics#2]
Hi. Thank you for the great work.
Do you have a plan to provide official HOTA results when we submit to the MOT Challenge Benchmark?

**Comment by JonathonLuiten** [comment]
Yes. Coming soon!!!!!

**Comment by jiaweihe1996** [comment]
Thank you very much. Looking forward to it!

**Comment by JonathonLuiten** [comment]
This is now implemented. Check out MOTChallenge.org for the results! :)
